# Prometheus Configuration for AI-BOS ERP
# This configuration sets up metrics collection and alerting

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "aibos-erp-dev"
    environment: "development"

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "aibos-bff"
    static_configs:
      - targets: ["host.docker.internal:3001"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "aibos-web"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
    metrics_path: "/metrics"
    scrape_interval: 15s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:8123"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
    metrics_path: "/metrics"
    scrape_interval: 15s
